### ISSUE TITLE
Verify GBIF DOI library is not useful

### ISSUE THREAD

**Issue by timrobertson100** [AtlasOfLivingAustralia/doi#1]
GBIF have robust Java libraries for DOI handling with EzID and DataCite. They might be useful to the ALA https://github.com/gbif/gbif-doi

**Comment by matthewandrews** [comment]
My impression (and @m-hope is the one dealing with this really) is that ANDS is the service we are using to create/manage DOIs.  This repo is really just a data store for static web content - the pages and downloadable pdf/csv/zip files associated with each DOI.

**Comment by matthewandrews** [comment]
However these libraries might be useful to ALA apps generating DOI pages/data... @m-r-c @PeggyNewman

**Comment by timrobertson100** [comment]
Thanks - I just wanted to try and save effort. If ANDS is a DataCite service, the library might help for thise Apps you mention. If ANDS supports the DataCite metadata kernel, but a different API, we would be happy to see that added into the GBIF project as a 3rd service.

Closing this issue as resolved.
